// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tac/liquidstake/v1beta1/authz.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AuthorizationType defines the type of staking module authorization type
//
// Since: cosmos-sdk 0.43
type AuthorizationType int32

const (
	AuthorizationType_AUTHORIZATION_TYPE_UNSPECIFIED AuthorizationType = 0
	AuthorizationType_AUTHORIZATION_TYPE_STAKE       AuthorizationType = 1
	AuthorizationType_AUTHORIZATION_TYPE_UNSTAKE     AuthorizationType = 2
	AuthorizationType_AUTHORIZATION_TYPE_STAKE_TO_LP AuthorizationType = 3
)

var AuthorizationType_name = map[int32]string{
	0: "AUTHORIZATION_TYPE_UNSPECIFIED",
	1: "AUTHORIZATION_TYPE_STAKE",
	2: "AUTHORIZATION_TYPE_UNSTAKE",
	3: "AUTHORIZATION_TYPE_STAKE_TO_LP",
}

var AuthorizationType_value = map[string]int32{
	"AUTHORIZATION_TYPE_UNSPECIFIED": 0,
	"AUTHORIZATION_TYPE_STAKE":       1,
	"AUTHORIZATION_TYPE_UNSTAKE":     2,
	"AUTHORIZATION_TYPE_STAKE_TO_LP": 3,
}

func (x AuthorizationType) String() string {
	return proto.EnumName(AuthorizationType_name, int32(x))
}

func (AuthorizationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3677b5f7745a7444, []int{0}
}

// StakeAuthorization defines authorization for delegate/undelegate/redelegate.
//
// Since: cosmos-sdk 0.43
type LiquidStakeAuthorization struct {
	// max_tokens specifies the maximum amount of tokens can be delegate to a validator. If it is
	// empty, there is no spend limit and any amount of coins can be delegated.
	MaxTokens *types.Coin `protobuf:"bytes,1,opt,name=max_tokens,json=maxTokens,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"max_tokens,omitempty"`
	// validators is the oneof that represents either allow_list or deny_list
	// authorization_type defines one of AuthorizationType.
	AuthorizationType AuthorizationType `protobuf:"varint,2,opt,name=authorization_type,json=authorizationType,proto3,enum=tac.liquidstake.v1beta1.AuthorizationType" json:"authorization_type,omitempty"`
	//ValidatorAdress in case of StakeToLP
	Validator string `protobuf:"bytes,3,opt,name=Validator,proto3" json:"Validator,omitempty"`
	//ValidatorAdress in case of StakeToLP
	MinLiquidTokens *types.Coin `protobuf:"bytes,4,opt,name=min_liquid_tokens,json=minLiquidTokens,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"min_liquid_tokens,omitempty"`
}

func (m *LiquidStakeAuthorization) Reset()         { *m = LiquidStakeAuthorization{} }
func (m *LiquidStakeAuthorization) String() string { return proto.CompactTextString(m) }
func (*LiquidStakeAuthorization) ProtoMessage()    {}
func (*LiquidStakeAuthorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_3677b5f7745a7444, []int{0}
}
func (m *LiquidStakeAuthorization) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidStakeAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidStakeAuthorization.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidStakeAuthorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidStakeAuthorization.Merge(m, src)
}
func (m *LiquidStakeAuthorization) XXX_Size() int {
	return m.Size()
}
func (m *LiquidStakeAuthorization) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidStakeAuthorization.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidStakeAuthorization proto.InternalMessageInfo

func (m *LiquidStakeAuthorization) GetMaxTokens() *types.Coin {
	if m != nil {
		return m.MaxTokens
	}
	return nil
}

func (m *LiquidStakeAuthorization) GetAuthorizationType() AuthorizationType {
	if m != nil {
		return m.AuthorizationType
	}
	return AuthorizationType_AUTHORIZATION_TYPE_UNSPECIFIED
}

func (m *LiquidStakeAuthorization) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *LiquidStakeAuthorization) GetMinLiquidTokens() *types.Coin {
	if m != nil {
		return m.MinLiquidTokens
	}
	return nil
}

func init() {
	proto.RegisterEnum("tac.liquidstake.v1beta1.AuthorizationType", AuthorizationType_name, AuthorizationType_value)
	proto.RegisterType((*LiquidStakeAuthorization)(nil), "tac.liquidstake.v1beta1.LiquidStakeAuthorization")
}

func init() {
	proto.RegisterFile("tac/liquidstake/v1beta1/authz.proto", fileDescriptor_3677b5f7745a7444)
}

var fileDescriptor_3677b5f7745a7444 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x49, 0x4c, 0xd6,
	0xcf, 0xc9, 0x2c, 0x2c, 0xcd, 0x4c, 0x29, 0x2e, 0x49, 0xcc, 0x4e, 0xd5, 0x2f, 0x33, 0x4c, 0x4a,
	0x2d, 0x49, 0x34, 0xd4, 0x4f, 0x2c, 0x2d, 0xc9, 0xa8, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x2f, 0x49, 0x4c, 0xd6, 0x43, 0x52, 0xa4, 0x07, 0x55, 0x24, 0x25, 0x92, 0x9e, 0x9f, 0x9e,
	0x0f, 0x56, 0xa3, 0x0f, 0x62, 0x41, 0x94, 0x4b, 0x49, 0x26, 0xe7, 0x17, 0xe7, 0xe6, 0x17, 0xc7,
	0x43, 0x24, 0x20, 0x1c, 0xa8, 0x94, 0x1c, 0x84, 0xa7, 0x9f, 0x94, 0x58, 0x8c, 0xb0, 0x2a, 0x39,
	0x3f, 0x33, 0x0f, 0x2a, 0x2f, 0x98, 0x98, 0x9b, 0x99, 0x97, 0xaf, 0x0f, 0x26, 0x21, 0x42, 0x4a,
	0x37, 0x99, 0xb9, 0x24, 0x7c, 0xc0, 0x76, 0x07, 0x83, 0xec, 0x76, 0x2c, 0x2d, 0xc9, 0xc8, 0x2f,
	0xca, 0xac, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0x13, 0x4a, 0xe5, 0xe2, 0xca, 0x4d, 0xac, 0x88, 0x2f,
	0xc9, 0xcf, 0x4e, 0xcd, 0x2b, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd4, 0x83, 0x5a,
	0x09, 0xb2, 0x04, 0xe6, 0x54, 0x3d, 0xe7, 0xfc, 0xcc, 0x3c, 0x27, 0xed, 0x55, 0xf7, 0xe5, 0xd5,
	0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xa1, 0x6e, 0x83, 0x52, 0xba, 0xc5,
	0x29, 0xd9, 0xfa, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0x60, 0xc5, 0x41, 0x9c, 0xb9, 0x89, 0x15, 0x21,
	0x60, 0x83, 0x85, 0x22, 0xb9, 0x84, 0x12, 0x91, 0xed, 0x8d, 0x07, 0x29, 0x93, 0x60, 0x52, 0x60,
	0xd4, 0xe0, 0x33, 0xd2, 0xd2, 0xc3, 0x11, 0x3a, 0x7a, 0x28, 0x4e, 0x0d, 0xa9, 0x2c, 0x48, 0x0d,
	0x12, 0x4c, 0x44, 0x17, 0x12, 0x32, 0xe3, 0xe2, 0x0c, 0x4b, 0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0xc9,
	0x2f, 0x92, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x74, 0x92, 0xb8, 0xb4, 0x45, 0x57, 0x04, 0xea, 0x07,
	0xc7, 0x94, 0x94, 0xa2, 0xd4, 0xe2, 0xe2, 0xe0, 0x92, 0xa2, 0xcc, 0xbc, 0xf4, 0x20, 0x84, 0x52,
	0xa1, 0x22, 0x2e, 0xc1, 0xdc, 0xcc, 0xbc, 0x78, 0x88, 0xbd, 0xb0, 0x00, 0x60, 0xa1, 0x6a, 0x00,
	0xf0, 0xe7, 0x66, 0xe6, 0x41, 0x42, 0x1e, 0x12, 0x0c, 0x56, 0xfe, 0xa7, 0xb6, 0xe8, 0x2a, 0x41,
	0xcd, 0x86, 0xa4, 0x0f, 0xac, 0x5e, 0xed, 0x7a, 0xbe, 0x41, 0x4b, 0x05, 0x39, 0x4d, 0xe1, 0x8a,
	0x3e, 0xad, 0x99, 0x8c, 0x5c, 0x82, 0x18, 0xa1, 0x24, 0xa4, 0xc4, 0x25, 0xe7, 0x18, 0x1a, 0xe2,
	0xe1, 0x1f, 0xe4, 0x19, 0xe5, 0x18, 0xe2, 0xe9, 0xef, 0x17, 0x1f, 0x12, 0x19, 0xe0, 0x1a, 0x1f,
	0xea, 0x17, 0x1c, 0xe0, 0xea, 0xec, 0xe9, 0xe6, 0xe9, 0xea, 0x22, 0xc0, 0x20, 0x24, 0xc3, 0x25,
	0x81, 0x45, 0x4d, 0x70, 0x88, 0xa3, 0xb7, 0xab, 0x00, 0xa3, 0x90, 0x1c, 0x97, 0x14, 0x76, 0x13,
	0xc0, 0xf2, 0x4c, 0x38, 0x6c, 0x00, 0xcb, 0xc6, 0x87, 0xf8, 0xc7, 0xfb, 0x04, 0x08, 0x30, 0x3b,
	0x39, 0x9f, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e,
	0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x26, 0x66, 0x00, 0xa6,
	0x96, 0xe5, 0xea, 0x57, 0xa0, 0xe4, 0x23, 0x70, 0x38, 0x26, 0xb1, 0x81, 0xd3, 0xb0, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0xf1, 0x07, 0x69, 0xd4, 0x67, 0x03, 0x00, 0x00,
}

func (m *LiquidStakeAuthorization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidStakeAuthorization) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidStakeAuthorization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinLiquidTokens != nil {
		{
			size, err := m.MinLiquidTokens.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAuthz(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintAuthz(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0x1a
	}
	if m.AuthorizationType != 0 {
		i = encodeVarintAuthz(dAtA, i, uint64(m.AuthorizationType))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxTokens != nil {
		{
			size, err := m.MaxTokens.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAuthz(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAuthz(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuthz(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LiquidStakeAuthorization) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxTokens != nil {
		l = m.MaxTokens.Size()
		n += 1 + l + sovAuthz(uint64(l))
	}
	if m.AuthorizationType != 0 {
		n += 1 + sovAuthz(uint64(m.AuthorizationType))
	}
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovAuthz(uint64(l))
	}
	if m.MinLiquidTokens != nil {
		l = m.MinLiquidTokens.Size()
		n += 1 + l + sovAuthz(uint64(l))
	}
	return n
}

func sovAuthz(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuthz(x uint64) (n int) {
	return sovAuthz(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LiquidStakeAuthorization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidStakeAuthorization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidStakeAuthorization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MaxTokens == nil {
				m.MaxTokens = &types.Coin{}
			}
			if err := m.MaxTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizationType", wireType)
			}
			m.AuthorizationType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuthorizationType |= AuthorizationType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLiquidTokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthz
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthz
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MinLiquidTokens == nil {
				m.MinLiquidTokens = &types.Coin{}
			}
			if err := m.MinLiquidTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthz(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthz
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuthz(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuthz
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthz
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuthz
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuthz
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuthz
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuthz        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuthz          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuthz = fmt.Errorf("proto: unexpected end of group")
)
