// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package liquidstakev1beta1

import (
	_ "cosmossdk.io/api/amino"
	v1beta1 "cosmossdk.io/api/cosmos/base/v1beta1"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_LiquidStakeAuthorization                    protoreflect.MessageDescriptor
	fd_LiquidStakeAuthorization_max_tokens         protoreflect.FieldDescriptor
	fd_LiquidStakeAuthorization_authorization_type protoreflect.FieldDescriptor
	fd_LiquidStakeAuthorization_Validator          protoreflect.FieldDescriptor
	fd_LiquidStakeAuthorization_min_liquid_tokens  protoreflect.FieldDescriptor
)

func init() {
	file_pstake_liquidstake_v1beta1_authz_proto_init()
	md_LiquidStakeAuthorization = File_pstake_liquidstake_v1beta1_authz_proto.Messages().ByName("LiquidStakeAuthorization")
	fd_LiquidStakeAuthorization_max_tokens = md_LiquidStakeAuthorization.Fields().ByName("max_tokens")
	fd_LiquidStakeAuthorization_authorization_type = md_LiquidStakeAuthorization.Fields().ByName("authorization_type")
	fd_LiquidStakeAuthorization_Validator = md_LiquidStakeAuthorization.Fields().ByName("Validator")
	fd_LiquidStakeAuthorization_min_liquid_tokens = md_LiquidStakeAuthorization.Fields().ByName("min_liquid_tokens")
}

var _ protoreflect.Message = (*fastReflection_LiquidStakeAuthorization)(nil)

type fastReflection_LiquidStakeAuthorization LiquidStakeAuthorization

func (x *LiquidStakeAuthorization) ProtoReflect() protoreflect.Message {
	return (*fastReflection_LiquidStakeAuthorization)(x)
}

func (x *LiquidStakeAuthorization) slowProtoReflect() protoreflect.Message {
	mi := &file_pstake_liquidstake_v1beta1_authz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_LiquidStakeAuthorization_messageType fastReflection_LiquidStakeAuthorization_messageType
var _ protoreflect.MessageType = fastReflection_LiquidStakeAuthorization_messageType{}

type fastReflection_LiquidStakeAuthorization_messageType struct{}

func (x fastReflection_LiquidStakeAuthorization_messageType) Zero() protoreflect.Message {
	return (*fastReflection_LiquidStakeAuthorization)(nil)
}
func (x fastReflection_LiquidStakeAuthorization_messageType) New() protoreflect.Message {
	return new(fastReflection_LiquidStakeAuthorization)
}
func (x fastReflection_LiquidStakeAuthorization_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_LiquidStakeAuthorization
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_LiquidStakeAuthorization) Descriptor() protoreflect.MessageDescriptor {
	return md_LiquidStakeAuthorization
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_LiquidStakeAuthorization) Type() protoreflect.MessageType {
	return _fastReflection_LiquidStakeAuthorization_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_LiquidStakeAuthorization) New() protoreflect.Message {
	return new(fastReflection_LiquidStakeAuthorization)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_LiquidStakeAuthorization) Interface() protoreflect.ProtoMessage {
	return (*LiquidStakeAuthorization)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_LiquidStakeAuthorization) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.MaxTokens != nil {
		value := protoreflect.ValueOfMessage(x.MaxTokens.ProtoReflect())
		if !f(fd_LiquidStakeAuthorization_max_tokens, value) {
			return
		}
	}
	if x.AuthorizationType != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.AuthorizationType))
		if !f(fd_LiquidStakeAuthorization_authorization_type, value) {
			return
		}
	}
	if x.Validator != "" {
		value := protoreflect.ValueOfString(x.Validator)
		if !f(fd_LiquidStakeAuthorization_Validator, value) {
			return
		}
	}
	if x.MinLiquidTokens != nil {
		value := protoreflect.ValueOfMessage(x.MinLiquidTokens.ProtoReflect())
		if !f(fd_LiquidStakeAuthorization_min_liquid_tokens, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_LiquidStakeAuthorization) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.max_tokens":
		return x.MaxTokens != nil
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.authorization_type":
		return x.AuthorizationType != 0
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.Validator":
		return x.Validator != ""
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.min_liquid_tokens":
		return x.MinLiquidTokens != nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pstake.liquidstake.v1beta1.LiquidStakeAuthorization"))
		}
		panic(fmt.Errorf("message pstake.liquidstake.v1beta1.LiquidStakeAuthorization does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LiquidStakeAuthorization) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.max_tokens":
		x.MaxTokens = nil
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.authorization_type":
		x.AuthorizationType = 0
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.Validator":
		x.Validator = ""
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.min_liquid_tokens":
		x.MinLiquidTokens = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pstake.liquidstake.v1beta1.LiquidStakeAuthorization"))
		}
		panic(fmt.Errorf("message pstake.liquidstake.v1beta1.LiquidStakeAuthorization does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_LiquidStakeAuthorization) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.max_tokens":
		value := x.MaxTokens
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.authorization_type":
		value := x.AuthorizationType
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.Validator":
		value := x.Validator
		return protoreflect.ValueOfString(value)
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.min_liquid_tokens":
		value := x.MinLiquidTokens
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pstake.liquidstake.v1beta1.LiquidStakeAuthorization"))
		}
		panic(fmt.Errorf("message pstake.liquidstake.v1beta1.LiquidStakeAuthorization does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LiquidStakeAuthorization) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.max_tokens":
		x.MaxTokens = value.Message().Interface().(*v1beta1.Coin)
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.authorization_type":
		x.AuthorizationType = (AuthorizationType)(value.Enum())
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.Validator":
		x.Validator = value.Interface().(string)
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.min_liquid_tokens":
		x.MinLiquidTokens = value.Message().Interface().(*v1beta1.Coin)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pstake.liquidstake.v1beta1.LiquidStakeAuthorization"))
		}
		panic(fmt.Errorf("message pstake.liquidstake.v1beta1.LiquidStakeAuthorization does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LiquidStakeAuthorization) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.max_tokens":
		if x.MaxTokens == nil {
			x.MaxTokens = new(v1beta1.Coin)
		}
		return protoreflect.ValueOfMessage(x.MaxTokens.ProtoReflect())
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.min_liquid_tokens":
		if x.MinLiquidTokens == nil {
			x.MinLiquidTokens = new(v1beta1.Coin)
		}
		return protoreflect.ValueOfMessage(x.MinLiquidTokens.ProtoReflect())
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.authorization_type":
		panic(fmt.Errorf("field authorization_type of message pstake.liquidstake.v1beta1.LiquidStakeAuthorization is not mutable"))
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.Validator":
		panic(fmt.Errorf("field Validator of message pstake.liquidstake.v1beta1.LiquidStakeAuthorization is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pstake.liquidstake.v1beta1.LiquidStakeAuthorization"))
		}
		panic(fmt.Errorf("message pstake.liquidstake.v1beta1.LiquidStakeAuthorization does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_LiquidStakeAuthorization) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.max_tokens":
		m := new(v1beta1.Coin)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.authorization_type":
		return protoreflect.ValueOfEnum(0)
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.Validator":
		return protoreflect.ValueOfString("")
	case "pstake.liquidstake.v1beta1.LiquidStakeAuthorization.min_liquid_tokens":
		m := new(v1beta1.Coin)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: pstake.liquidstake.v1beta1.LiquidStakeAuthorization"))
		}
		panic(fmt.Errorf("message pstake.liquidstake.v1beta1.LiquidStakeAuthorization does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_LiquidStakeAuthorization) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in pstake.liquidstake.v1beta1.LiquidStakeAuthorization", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_LiquidStakeAuthorization) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_LiquidStakeAuthorization) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_LiquidStakeAuthorization) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_LiquidStakeAuthorization) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*LiquidStakeAuthorization)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.MaxTokens != nil {
			l = options.Size(x.MaxTokens)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.AuthorizationType != 0 {
			n += 1 + runtime.Sov(uint64(x.AuthorizationType))
		}
		l = len(x.Validator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.MinLiquidTokens != nil {
			l = options.Size(x.MinLiquidTokens)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*LiquidStakeAuthorization)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.MinLiquidTokens != nil {
			encoded, err := options.Marshal(x.MinLiquidTokens)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Validator) > 0 {
			i -= len(x.Validator)
			copy(dAtA[i:], x.Validator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Validator)))
			i--
			dAtA[i] = 0x1a
		}
		if x.AuthorizationType != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.AuthorizationType))
			i--
			dAtA[i] = 0x10
		}
		if x.MaxTokens != nil {
			encoded, err := options.Marshal(x.MaxTokens)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*LiquidStakeAuthorization)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: LiquidStakeAuthorization: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: LiquidStakeAuthorization: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MaxTokens", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.MaxTokens == nil {
					x.MaxTokens = &v1beta1.Coin{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.MaxTokens); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AuthorizationType", wireType)
				}
				x.AuthorizationType = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.AuthorizationType |= AuthorizationType(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Validator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MinLiquidTokens", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.MinLiquidTokens == nil {
					x.MinLiquidTokens = &v1beta1.Coin{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.MinLiquidTokens); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: pstake/liquidstake/v1beta1/authz.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthorizationType defines the type of staking module authorization type
//
// Since: cosmos-sdk 0.43
type AuthorizationType int32

const (
	AuthorizationType_AUTHORIZATION_TYPE_UNSPECIFIED AuthorizationType = 0
	AuthorizationType_AUTHORIZATION_TYPE_STAKE       AuthorizationType = 1
	AuthorizationType_AUTHORIZATION_TYPE_UNSTAKE     AuthorizationType = 2
	AuthorizationType_AUTHORIZATION_TYPE_STAKE_TO_LP AuthorizationType = 3
)

// Enum value maps for AuthorizationType.
var (
	AuthorizationType_name = map[int32]string{
		0: "AUTHORIZATION_TYPE_UNSPECIFIED",
		1: "AUTHORIZATION_TYPE_STAKE",
		2: "AUTHORIZATION_TYPE_UNSTAKE",
		3: "AUTHORIZATION_TYPE_STAKE_TO_LP",
	}
	AuthorizationType_value = map[string]int32{
		"AUTHORIZATION_TYPE_UNSPECIFIED": 0,
		"AUTHORIZATION_TYPE_STAKE":       1,
		"AUTHORIZATION_TYPE_UNSTAKE":     2,
		"AUTHORIZATION_TYPE_STAKE_TO_LP": 3,
	}
)

func (x AuthorizationType) Enum() *AuthorizationType {
	p := new(AuthorizationType)
	*p = x
	return p
}

func (x AuthorizationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pstake_liquidstake_v1beta1_authz_proto_enumTypes[0].Descriptor()
}

func (AuthorizationType) Type() protoreflect.EnumType {
	return &file_pstake_liquidstake_v1beta1_authz_proto_enumTypes[0]
}

func (x AuthorizationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationType.Descriptor instead.
func (AuthorizationType) EnumDescriptor() ([]byte, []int) {
	return file_pstake_liquidstake_v1beta1_authz_proto_rawDescGZIP(), []int{0}
}

// StakeAuthorization defines authorization for delegate/undelegate/redelegate.
//
// Since: cosmos-sdk 0.43
type LiquidStakeAuthorization struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// max_tokens specifies the maximum amount of tokens can be delegate to a validator. If it is
	// empty, there is no spend limit and any amount of coins can be delegated.
	MaxTokens *v1beta1.Coin `protobuf:"bytes,1,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// validators is the oneof that represents either allow_list or deny_list
	// authorization_type defines one of AuthorizationType.
	AuthorizationType AuthorizationType `protobuf:"varint,2,opt,name=authorization_type,json=authorizationType,proto3,enum=pstake.liquidstake.v1beta1.AuthorizationType" json:"authorization_type,omitempty"`
	// ValidatorAdress in case of StakeToLP
	Validator string `protobuf:"bytes,3,opt,name=Validator,proto3" json:"Validator,omitempty"`
	// ValidatorAdress in case of StakeToLP
	MinLiquidTokens *v1beta1.Coin `protobuf:"bytes,4,opt,name=min_liquid_tokens,json=minLiquidTokens,proto3" json:"min_liquid_tokens,omitempty"`
}

func (x *LiquidStakeAuthorization) Reset() {
	*x = LiquidStakeAuthorization{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pstake_liquidstake_v1beta1_authz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiquidStakeAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiquidStakeAuthorization) ProtoMessage() {}

// Deprecated: Use LiquidStakeAuthorization.ProtoReflect.Descriptor instead.
func (*LiquidStakeAuthorization) Descriptor() ([]byte, []int) {
	return file_pstake_liquidstake_v1beta1_authz_proto_rawDescGZIP(), []int{0}
}

func (x *LiquidStakeAuthorization) GetMaxTokens() *v1beta1.Coin {
	if x != nil {
		return x.MaxTokens
	}
	return nil
}

func (x *LiquidStakeAuthorization) GetAuthorizationType() AuthorizationType {
	if x != nil {
		return x.AuthorizationType
	}
	return AuthorizationType_AUTHORIZATION_TYPE_UNSPECIFIED
}

func (x *LiquidStakeAuthorization) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *LiquidStakeAuthorization) GetMinLiquidTokens() *v1beta1.Coin {
	if x != nil {
		return x.MinLiquidTokens
	}
	return nil
}

var File_pstake_liquidstake_v1beta1_authz_proto protoreflect.FileDescriptor

var file_pstake_liquidstake_v1beta1_authz_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x2f, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x73,
	0x74, 0x61, 0x6b, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x61, 0x75, 0x74,
	0x68, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x70, 0x73, 0x74, 0x61, 0x6b, 0x65,
	0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x2e, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x62, 0x61,
	0x73, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x63, 0x6f, 0x69, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69,
	0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdc, 0x03, 0x0a, 0x18, 0x4c, 0x69, 0x71,
	0x75, 0x69, 0x64, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x65, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x43, 0x6f, 0x69, 0x6e, 0x42, 0x2b, 0xaa, 0xdf, 0x1f, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x69,
	0x6e, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x12, 0x5c, 0x0a, 0x12,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x70, 0x73, 0x74, 0x61, 0x6b,
	0x65, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x2e, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x11, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x18, 0xd2,
	0xb4, 0x2d, 0x14, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x72, 0x0a, 0x11, 0x6d, 0x69, 0x6e, 0x5f, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x42, 0x2b, 0xaa, 0xdf, 0x1f, 0x27, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x0f, 0x6d, 0x69, 0x6e, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x3a, 0x4f, 0xca, 0xb4, 0x2d, 0x22, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x8a, 0xe7,
	0xb0, 0x2a, 0x24, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x2f, 0x4c,
	0x69, 0x71, 0x75, 0x69, 0x64, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x99, 0x01, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a,
	0x1e, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x1c, 0x0a, 0x18, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x4b, 0x45, 0x10, 0x01, 0x12,
	0x1e, 0x0a, 0x1a, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x54, 0x41, 0x4b, 0x45, 0x10, 0x02, 0x12,
	0x22, 0x0a, 0x1e, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x4b, 0x45, 0x5f, 0x54, 0x4f, 0x5f, 0x4c,
	0x50, 0x10, 0x03, 0x42, 0xf6, 0x01, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x73, 0x74, 0x61,
	0x6b, 0x65, 0x2e, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x2e, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x42, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x7a, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e,
	0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x2f, 0x6c, 0x69,
	0x71, 0x75, 0x69, 0x64, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x3b, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x76, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0xa2, 0x02, 0x03, 0x50, 0x4c, 0x58, 0xaa, 0x02, 0x1a, 0x50, 0x73, 0x74,
	0x61, 0x6b, 0x65, 0x2e, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x2e,
	0x56, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0xca, 0x02, 0x1a, 0x50, 0x73, 0x74, 0x61, 0x6b, 0x65,
	0x5c, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x5c, 0x56, 0x31, 0x62,
	0x65, 0x74, 0x61, 0x31, 0xe2, 0x02, 0x26, 0x50, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x5c, 0x4c, 0x69,
	0x71, 0x75, 0x69, 0x64, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x5c, 0x56, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x1c,
	0x50, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x3a, 0x3a, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x73, 0x74,
	0x61, 0x6b, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pstake_liquidstake_v1beta1_authz_proto_rawDescOnce sync.Once
	file_pstake_liquidstake_v1beta1_authz_proto_rawDescData = file_pstake_liquidstake_v1beta1_authz_proto_rawDesc
)

func file_pstake_liquidstake_v1beta1_authz_proto_rawDescGZIP() []byte {
	file_pstake_liquidstake_v1beta1_authz_proto_rawDescOnce.Do(func() {
		file_pstake_liquidstake_v1beta1_authz_proto_rawDescData = protoimpl.X.CompressGZIP(file_pstake_liquidstake_v1beta1_authz_proto_rawDescData)
	})
	return file_pstake_liquidstake_v1beta1_authz_proto_rawDescData
}

var file_pstake_liquidstake_v1beta1_authz_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pstake_liquidstake_v1beta1_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pstake_liquidstake_v1beta1_authz_proto_goTypes = []interface{}{
	(AuthorizationType)(0),           // 0: pstake.liquidstake.v1beta1.AuthorizationType
	(*LiquidStakeAuthorization)(nil), // 1: pstake.liquidstake.v1beta1.LiquidStakeAuthorization
	(*v1beta1.Coin)(nil),             // 2: cosmos.base.v1beta1.Coin
}
var file_pstake_liquidstake_v1beta1_authz_proto_depIdxs = []int32{
	2, // 0: pstake.liquidstake.v1beta1.LiquidStakeAuthorization.max_tokens:type_name -> cosmos.base.v1beta1.Coin
	0, // 1: pstake.liquidstake.v1beta1.LiquidStakeAuthorization.authorization_type:type_name -> pstake.liquidstake.v1beta1.AuthorizationType
	2, // 2: pstake.liquidstake.v1beta1.LiquidStakeAuthorization.min_liquid_tokens:type_name -> cosmos.base.v1beta1.Coin
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pstake_liquidstake_v1beta1_authz_proto_init() }
func file_pstake_liquidstake_v1beta1_authz_proto_init() {
	if File_pstake_liquidstake_v1beta1_authz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pstake_liquidstake_v1beta1_authz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiquidStakeAuthorization); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pstake_liquidstake_v1beta1_authz_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pstake_liquidstake_v1beta1_authz_proto_goTypes,
		DependencyIndexes: file_pstake_liquidstake_v1beta1_authz_proto_depIdxs,
		EnumInfos:         file_pstake_liquidstake_v1beta1_authz_proto_enumTypes,
		MessageInfos:      file_pstake_liquidstake_v1beta1_authz_proto_msgTypes,
	}.Build()
	File_pstake_liquidstake_v1beta1_authz_proto = out.File
	file_pstake_liquidstake_v1beta1_authz_proto_rawDesc = nil
	file_pstake_liquidstake_v1beta1_authz_proto_goTypes = nil
	file_pstake_liquidstake_v1beta1_authz_proto_depIdxs = nil
}
